### ISSUE TITLE
Composer will deprecate upper case characters in package name

### ISSUE THREAD

**Issue by FerhanGit** [Rehyved/openid-connect-client-php#7]
Hello, as the title describes it seems that newer version of composer will deprecate the upper case characters in package name. Do you consider any modification regarding this ?

**Comment by mpwaldhorst** [comment]
Hi @FerhanGit,
Thanks for creating this ticket.
I will need to verify if other changes are needed. 

Do you have a link or a way to get more information on this?
Are you getting warnings when running composer?

Thank you for any info you can provide.

**Comment by FerhanGit** [comment]
Hi, @mpwaldhorst
Yes, I have a warning when running composer - `Deprecation warning: require.Rehyved/openid-connect-client-php is invalid, it should not contain uppercase characters. Please use rehyved/openid-connect-client-php instead. Make sure you fix this as Composer 2.0 will error.`

**Comment by mpwaldhorst** [comment]
Hi @FerhanGit,
I think this warning is referring to the syntax used in your `composer.json` file.
If you change the require there to use lower case (so `rehyved/openid-connect-client-php`) it should fix that warning.

**Comment by FerhanGit** [comment]
Yes, you are right. Changing it to lower case in my composer.json file fixed the warning. Thank you for the help!
